name: Unit Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Conda Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - name: Lint with flake8
        run: |
          conda install flake8
          flake8 --extend-ignore=W191,E501,E128,E124
      - name: Test with pytest
        run: |
          conda install pytest
          pytest