name: Unit Tests

on:
  - push
  - pull_request

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
        python-version: ["3.8", "3.9", "3.10", "3.11",]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install tox tox-gh-actions
          pip install tox-conda
          
      - name: Conda list
        run: conda list

      - name: Test with tox
        run: tox
