name: Unit Tests

on:
  - push
  - pull_request

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
        python-version: ["3.8", "3.9", "3.10", "3.11",]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: testenv
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Install dependencies
        run: |
          conda install pip setuptools wheel tox

      - name: Conda list
        run: conda list

      - name: Test with tox
        run: tox -e testenv -rvv
