name: Unit Tests

on:
  - push
  - pull_request

jobs:
  Test-Package:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11",]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Install Dependencies Ubuntu
        if: matrix.os ==  'ubuntu-latest'
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Install Dependencies Windows
        if: matrix.os ==  'windows-latest'
        run: |
          conda install pip tox

      - name: Test with tox
        shell: bash -el {0}
        run: tox -r