name: Unit Tests

on:
  - push
  - pull_request

jobs:
  Test-Package:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11",]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Conda Environment
        if: matrix.os ==  'windows-latest'
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Set Up Python Ubuntu
        uses: actions/setup-python@v4
        if: matrix.os ==  'ubuntu-latest'
        with:
          python-version: ${{ matrix.python-version }}

      - name: Apt Package Cache Update  
        if: matrix.os ==  'ubuntu-latest'
        run: sudo apt-get update

      - name: Install GDAL Ubuntu      
        if: matrix.os ==  'ubuntu-latest'
        run: |
          sudo apt-get install gdal-bin libgdal-dev
          echo "CPLUS_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV
          echo "C_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV
          ogrversion=`ogrinfo --version | grep -oP "\d+\.\d+\.\d+"`
          echo "OGRVERSION=$ogrversion" >> $GITHUB_ENV

      - name: Install Dependencies Ubuntu
        if: matrix.os ==  'ubuntu-latest'
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
          python -m pip install 'gdal==${{ env.OGRVERSION }}'
          python -m pip install -r requirements.txt

      - name: Install Dependencies Windows
        if: matrix.os ==  'windows-latest'
        run: |
          conda install pip "tox<4"
          pip install "tox-gh-actions<2" tox-conda

      - name: Test with tox
        shell: bash -el {0}
        run: tox --skip-pkg-install
